<a href="https://colab.research.google.com/github/Steeve3/Titanic-ml/blob/main/notebooks/Project%20Titanic%20-%20Visual%20Textbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Introduction

# 2. Load Data
In this project dataset is downloaded using Kaggle API. This for the purpose on understanding how it can be done for future projects. Then after the loading of data and the set up, we will proceed with the exploration of the data.

In [1]:
!pip install kaggle -quiet

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2025.11.12)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.4.4)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.5)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.5.1)

In [8]:
# Upload the file with the access token
from google.colab import files
import os, shutil

# Upload the access_token file you downloaded from Kaggle
files.upload()  # select kaggle.json containing {"username":"xx","key":"KEY"}

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"stefanor22","key":"KGAT_9293ea8a5a953368e7a9fe4532a72a52"}\n'}

In [9]:
# create kaggle directory
!mkdir ~/.kaggle

mkdir: cannot create directory ‘/root/.kaggle’: File exists

In [10]:
#copy the file in the kaggle folder
!cp kaggle.json ~/.kaggle

In [11]:
# check the permissions
!ls -ltr ~/.kaggle

total 4
-rw-r--r-- 1 root root 72 Nov 23 17:58 kaggle.json

In [12]:
# change the permissions
!chmod 600 ~/.kaggle/kaggle.json

In [13]:
!ls -ltr ~/.kaggle

total 4
-rw------- 1 root root 72 Nov 23 17:58 kaggle.json

In [16]:
#download Titanic competition
!kaggle competitions download titanic -w -o -q
!unzip -o data/titanic.zip -d data/

401 Client Error: Unauthorized for url: https://www.kaggle.com/api/v1/competitions/data/download-all/titanic

# 3. EDA

I just set my Kaggle API token for this session in Colab. Now the data are accessible for EDA.

In [24]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

rw_training = pd.read_csv('/content/data/train.csv')
rw_test = pd.read_csv('/content/data/test.csv')
print('Here the dataset: \nTraining size {}, \nTest size {}'.format(rw_training.shape, rw_test.shape))

Here the dataset:
Training size (891, 12),
Test size (418, 11)

## Short exploration of the Traning Set

In [29]:
rw_training.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [30]:
rw_training.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [28]:
rw_training.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## Short Exploration of the Test set

#5. Feature Engineering
#6. Train/Test Split
#7. Modeling Pipelines
#8. Perceptron
#9. KNN
#10. SVM (Linear & RBF)
#11. Logistic Regression
#12. Decision Tree
#13. Random Forest
#14. Neural Network (MLP)
#15. Hyperparameter Tuning
#16. Model Comparison
#17. Conclusion
#18. Appendix (Theory Images)